<a href="https://colab.research.google.com/github/hwankang/Deep-Chemometrics/blob/master/09_Nov_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
import numpy as np
import pandas as pd

# Series 객체

In [87]:
s=pd.Series([0,0.25,8])

In [88]:
s.values

array([0.  , 0.25, 8.  ])

In [89]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [90]:
s[1]

0.25

In [91]:
s[1:3]

1    0.25
2    8.00
dtype: float64

In [92]:
s=pd.Series([0, 0.25, 0.5, 0.75,1.0],
            index=['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [93]:
s['e']

1.0

In [94]:
s[['c','d','e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [95]:
'b'in s

True

In [96]:
s=pd.Series([0,0.25,0.5,0.75],
            index=[2,4,6,7])
s

2    0.00
4    0.25
6    0.50
7    0.75
dtype: float64

In [97]:
s[4]

0.25

In [99]:
s[2:]

6    0.50
7    0.75
dtype: float64

In [100]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75])

In [101]:
s.value_counts()

0.00    1
0.25    1
0.50    1
0.75    1
dtype: int64

In [102]:
s.isin([0.25,0.5])

2    False
4     True
6     True
7    False
dtype: bool

In [103]:
pop_tuple={'서울': 9700000,
           '인천': 3400000,
           '부산': 5600000,
           '대구': 2000000,
           '광주':1000000,
           '대전': 4500000}
population = pd.Series(pop_tuple)
population

서울    9700000
인천    3400000
부산    5600000
대구    2000000
광주    1000000
대전    4500000
dtype: int64

In [104]:
population['서울']

9700000

In [105]:
population['서울':'부산']

서울    9700000
인천    3400000
부산    5600000
dtype: int64

#DataFrame 객체


In [106]:
pd.DataFrame([{'A':2,'B':4,'D':3}, {'A':4, 'B':5,'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [107]:
pd.DataFrame(np.random.rand(5,5),
             columns=['A','B','C','D','E'],
             index=[1,2,3,4,5])

A         B         C         D         E
1  0.015227  0.513500  0.448882  0.536111  0.746071
2  0.379915  0.223170  0.110765  0.482200  0.797449
3  0.198317  0.626669  0.869001  0.854178  0.428783
4  0.443645  0.503727  0.564468  0.202069  0.601650
5  0.550765  0.051212  0.412218  0.914716  0.197570

In [108]:
male_tuple={'서울': 970000,
           '인천': 340000,
           '부산': 560000,
           '대구': 200000,
           '광주':100000,
           '대전': 450000}
male=pd.Series(male_tuple)
male

서울    970000
인천    340000
부산    560000
대구    200000
광주    100000
대전    450000
dtype: int64

In [109]:
female_tuple={'서울': 97000,
           '인천': 34000,
           '부산': 56000,
           '대구': 20000,
           '광주':10000,
           '대전': 45000}
female=pd.Series(female_tuple)
female

서울    97000
인천    34000
부산    56000
대구    20000
광주    10000
대전    45000
dtype: int64

In [110]:
korea_df=pd.DataFrame({'인구수':population,
                       '남자수':male,
                       '여자수':female})
korea_df

인구수     남자수    여자수
서울  9700000  970000  97000
인천  3400000  340000  34000
부산  5600000  560000  56000
대구  2000000  200000  20000
광주  1000000  100000  10000
대전  4500000  450000  45000

In [111]:
korea_df.index

Index(['서울', '인천', '부산', '대구', '광주', '대전'], dtype='object')

In [112]:
korea_df.columns

Index(['인구수', '남자수', '여자수'], dtype='object')

In [113]:
korea_df['여자수']

서울    97000
인천    34000
부산    56000
대구    20000
광주    10000
대전    45000
Name: 여자수, dtype: int64

In [114]:
korea_df['서울':'인천']

인구수     남자수    여자수
서울  9700000  970000  97000
인천  3400000  340000  34000

#index 객체

In [115]:
idx = pd.Index([2,4,6,8,10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [116]:
idx[1]

4

In [117]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [118]:
idx[-1::]

Int64Index([10], dtype='int64')

In [119]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [120]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx,type)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
Int64Index([2, 4, 6, 8, 10], dtype='int64') <class 'type'>


# index 연산

In [121]:
idx1 = pd.Index([1,2,4,6,8])
idx2 =pd.Index([2,4,5,6,7])
print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1.intersection(idx2))
print(idx1&idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
idx1.drop(2)
idx1 ^ idx2

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  # This is added back by InteractiveShellApp.init_path()


Int64Index([1, 5, 7, 8], dtype='int64')

#인덱싱

In [122]:
s=pd.Series([0,0.25,0.5,0.75,1.0],
            index=['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [123]:
s['b']

0.25

In [124]:
'b' in s 

True

In [125]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [126]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [127]:
s['f']=1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [128]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [129]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [130]:
s[(s>0.4)&(s<0.8)]

c    0.50
d    0.75
dtype: float64

In [131]:
s[['a','c','e']]

a    0.0
c    0.5
e    1.0
dtype: float64

#Series 인덱싱

In [132]:
s = pd.Series(['a','b','c','d','e'],
              index=[1,3,5,7,9])
s[1]
s[2:4]
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [133]:
s
s.iloc[1]

'b'

In [134]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [135]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [136]:
s.reindex(range(10),method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

# DataFrame 인덱싱

In [137]:
korea_df['남자수']

서울    970000
인천    340000
부산    560000
대구    200000
광주    100000
대전    450000
Name: 남자수, dtype: int64

In [138]:
korea_df.여자수

서울    97000
인천    34000
부산    56000
대구    20000
광주    10000
대전    45000
Name: 여자수, dtype: int64

In [139]:
korea_df['남녀비율']=(korea_df['남자수']*100/korea_df['여자수'])

In [141]:
korea_df.남녀비율

서울    1000.0
인천    1000.0
부산    1000.0
대구    1000.0
광주    1000.0
대전    1000.0
Name: 남녀비율, dtype: float64

In [142]:
korea_df.values

array([[9.7e+06, 9.7e+05, 9.7e+04, 1.0e+03],
       [3.4e+06, 3.4e+05, 3.4e+04, 1.0e+03],
       [5.6e+06, 5.6e+05, 5.6e+04, 1.0e+03],
       [2.0e+06, 2.0e+05, 2.0e+04, 1.0e+03],
       [1.0e+06, 1.0e+05, 1.0e+04, 1.0e+03],
       [4.5e+06, 4.5e+05, 4.5e+04, 1.0e+03]])

In [143]:
korea_df.T

서울         인천         부산         대구         광주         대전
인구수   9700000.0  3400000.0  5600000.0  2000000.0  1000000.0  4500000.0
남자수    970000.0   340000.0   560000.0   200000.0   100000.0   450000.0
여자수     97000.0    34000.0    56000.0    20000.0    10000.0    45000.0
남녀비율     1000.0     1000.0     1000.0     1000.0     1000.0     1000.0

In [144]:
korea_df.values[0]

array([9.7e+06, 9.7e+05, 9.7e+04, 1.0e+03])

In [145]:
korea_df['인구수']

서울    9700000
인천    3400000
부산    5600000
대구    2000000
광주    1000000
대전    4500000
Name: 인구수, dtype: int64

In [147]:
korea_df.loc[:'인천',:'남자수']

인구수     남자수
서울  9700000  970000
인천  3400000  340000

In [151]:
korea_df.loc[(korea_df.여자수 >10000)]

인구수     남자수    여자수    남녀비율
서울  9700000  970000  97000  1000.0
인천  3400000  340000  34000  1000.0
부산  5600000  560000  56000  1000.0
대구  2000000  200000  20000  1000.0
대전  4500000  450000  45000  1000.0

In [152]:
korea_df.loc[(korea_df.인구수 <2000000)]

인구수     남자수    여자수    남녀비율
광주  1000000  100000  10000  1000.0

In [154]:
korea_df.loc()[korea_df.남녀비율>100]

인구수     남자수    여자수    남녀비율
서울  9700000  970000  97000  1000.0
인천  3400000  340000  34000  1000.0
부산  5600000  560000  56000  1000.0
대구  2000000  200000  20000  1000.0
광주  1000000  100000  10000  1000.0
대전  4500000  450000  45000  1000.0

In [156]:
korea_df.loc[(korea_df.인구수> 20000) & (korea_df.남녀비율>100)]

인구수     남자수    여자수    남녀비율
서울  9700000  970000  97000  1000.0
인천  3400000  340000  34000  1000.0
부산  5600000  560000  56000  1000.0
대구  2000000  200000  20000  1000.0
광주  1000000  100000  10000  1000.0
대전  4500000  450000  45000  1000.0

In [157]:
korea_df.iloc[:3,:2]

인구수     남자수
서울  9700000  970000
인천  3400000  340000
부산  5600000  560000

# 다중 인덱싱 Series

In [158]:
idx_tuples=[('서울시',2010),('서울시',2020),
            ('부산시',2010),('부산시',2020),
            ('인천시',2010),('인천시',2020),
            ('대구시',2010),('대구시',2020),
            ('대전시',2010),('대전시',2020),
            ('광주시',2010),('광주시',2020)]
idx_tuples

[('서울시', 2010),
 ('서울시', 2020),
 ('부산시', 2010),
 ('부산시', 2020),
 ('인천시', 2010),
 ('인천시', 2020),
 ('대구시', 2010),
 ('대구시', 2020),
 ('대전시', 2010),
 ('대전시', 2020),
 ('광주시', 2010),
 ('광주시', 2020)]

In [160]:
pop_tuples=[10312545, 9720846,
            2567910,3404423,
            2757296,2947217,
            2511676,2427954,
            1503664,1471040,
            1454636,1455048]
population= pd.Series(pop_tuples,index=idx_tuples)
population

(서울시, 2010)    10312545
(서울시, 2020)     9720846
(부산시, 2010)     2567910
(부산시, 2020)     3404423
(인천시, 2010)     2757296
(인천시, 2020)     2947217
(대구시, 2010)     2511676
(대구시, 2020)     2427954
(대전시, 2010)     1503664
(대전시, 2020)     1471040
(광주시, 2010)     1454636
(광주시, 2020)     1455048
dtype: int64

In [161]:
midx=pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울시', 2010),
            ('서울시', 2020),
            ('부산시', 2010),
            ('부산시', 2020),
            ('인천시', 2010),
            ('인천시', 2020),
            ('대구시', 2010),
            ('대구시', 2020),
            ('대전시', 2010),
            ('대전시', 2020),
            ('광주시', 2010),
            ('광주시', 2020)],
           )

In [162]:
population = population.reindex(midx)

In [163]:
population

서울시  2010    10312545
     2020     9720846
부산시  2010     2567910
     2020     3404423
인천시  2010     2757296
     2020     2947217
대구시  2010     2511676
     2020     2427954
대전시  2010     1503664
     2020     1471040
광주시  2010     1454636
     2020     1455048
dtype: int64

In [164]:
population[:,2010]

서울시    10312545
부산시     2567910
인천시     2757296
대구시     2511676
대전시     1503664
광주시     1454636
dtype: int64

In [165]:
population['대전시',:]

2010    1503664
2020    1471040
dtype: int64

In [166]:
korea_mdf=population.unstack()
korea_mdf

2010     2020
광주시   1454636  1455048
대구시   2511676  2427954
대전시   1503664  1471040
부산시   2567910  3404423
서울시  10312545  9720846
인천시   2757296  2947217

In [167]:
korea_mdf.stack()

광주시  2010     1454636
     2020     1455048
대구시  2010     2511676
     2020     2427954
대전시  2010     1503664
     2020     1471040
부산시  2010     2567910
     2020     3404423
서울시  2010    10312545
     2020     9720846
인천시  2010     2757296
     2020     2947217
dtype: int64

In [168]:
male_tuples=[5111259,4732275,
            1773170,1668618,
            1390356,1476813,
            1255245,1198815,
            763648,734441,
            721780,720060]
male_tuples

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 763648,
 734441,
 721780,
 720060]

In [169]:
female_tuples=[5201286,4988571,
               1794740,1735805,
               1367940,1470404,
               1256431,1229139,
               750016,736599,
               732856,734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [170]:
korea_mdf=pd.DataFrame({'인구수':population,
                        '남자수':male_tuples,
                        '여자수':female_tuples})
korea_mdf

인구수      남자수      여자수
서울시 2010  10312545  5111259  5201286
    2020   9720846  4732275  4988571
부산시 2010   2567910  1773170  1794740
    2020   3404423  1668618  1735805
인천시 2010   2757296  1390356  1367940
    2020   2947217  1476813  1470404
대구시 2010   2511676  1255245  1256431
    2020   2427954  1198815  1229139
대전시 2010   1503664   763648   750016
    2020   1471040   734441   736599
광주시 2010   1454636   721780   732856
    2020   1455048   720060   734988

In [171]:
ratio=korea_mdf['남자수']*100/korea_mdf['여자수']
ratio

서울시  2010     98.269140
     2020     94.862336
부산시  2010     98.798155
     2020     96.129346
인천시  2010    101.638668
     2020    100.435867
대구시  2010     99.905606
     2020     97.532907
대전시  2010    101.817561
     2020     99.707032
광주시  2010     98.488653
     2020     97.968946
dtype: float64

In [172]:
ratio.unstack()

2010        2020
광주시   98.488653   97.968946
대구시   99.905606   97.532907
대전시  101.817561   99.707032
부산시   98.798155   96.129346
서울시   98.269140   94.862336
인천시  101.638668  100.435867

In [175]:
korea_mdf=pd.DataFrame({'인구수':population,
                        '남자수':male_tuples,
                        '여자수':female_tuples,
                       '남녀비율': ratio})
korea_mdf

인구수      남자수      여자수        남녀비율
서울시 2010  10312545  5111259  5201286   98.269140
    2020   9720846  4732275  4988571   94.862336
부산시 2010   2567910  1773170  1794740   98.798155
    2020   3404423  1668618  1735805   96.129346
인천시 2010   2757296  1390356  1367940  101.638668
    2020   2947217  1476813  1470404  100.435867
대구시 2010   2511676  1255245  1256431   99.905606
    2020   2427954  1198815  1229139   97.532907
대전시 2010   1503664   763648   750016  101.817561
    2020   1471040   734441   736599   99.707032
광주시 2010   1454636   721780   732856   98.488653
    2020   1455048   720060   734988   97.968946

#다중 인덱스 생성

In [177]:
df=pd.DataFrame(np.random.rand(6,3),
                index=[['a','a','b','b','c','c'],[1,2,1,2,1,2]],
                columns=['c1','c2','c3'])
df

c1        c2        c3
a 1  0.208192  0.895563  0.343156
  2  0.535355  0.990428  0.024437
b 1  0.168629  0.040680  0.447706
  2  0.718504  0.172731  0.221664
c 1  0.711647  0.539269  0.413489
  2  0.425549  0.422989  0.887609

In [178]:
pd.MultiIndex.from_arrays([['a','a','b','b','c','c'],[1,2,1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [180]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2),('c',1),('c',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [183]:
pd.MultiIndex.from_product([['a','b','c'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [185]:
pd.MultiIndex(levels=[['a','b','c'],[1,2]],
             codes=[[0,0,1,1,2,2],[0,1,0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [186]:
population

서울시  2010    10312545
     2020     9720846
부산시  2010     2567910
     2020     3404423
인천시  2010     2757296
     2020     2947217
대구시  2010     2511676
     2020     2427954
대전시  2010     1503664
     2020     1471040
광주시  2010     1454636
     2020     1455048
dtype: int64

In [187]:
population.index.names=['행정구역','년도']
population

행정구역  년도  
서울시   2010    10312545
      2020     9720846
부산시   2010     2567910
      2020     3404423
인천시   2010     2757296
      2020     2947217
대구시   2010     2511676
      2020     2427954
대전시   2010     1503664
      2020     1471040
광주시   2010     1454636
      2020     1455048
dtype: int64

In [192]:
idx=pd.MultiIndex.from_product([['a','b','c'],[1,2]],
                               names=['name1','name2'])
cols=pd.MultiIndex.from_product([['c1','c2','c3'],[1,2]],
                                names=['col_name1','col_name_2'])
data=np.round(np.random.randn(6,6),2)
mdf=pd.DataFrame(data,index=idx, columns=cols)
mdf

col_name1      c1          c2          c3      
col_name_2      1     2     1     2     1     2
name1 name2                                    
a     1     -0.05 -0.38 -0.09 -0.68 -0.16  0.99
      2      0.57 -1.94  0.21  2.73  1.10  0.72
b     1     -1.31  0.04  1.25  0.43 -0.81  0.77
      2     -1.70  0.65  1.52  0.63  1.20  0.12
c     1      0.55 -0.86  1.31 -0.75 -0.93 -1.86
      2      0.41 -1.45 -0.20 -1.08  1.07 -0.03

In [193]:
mdf['c2']

col_name_2      1     2
name1 name2            
a     1     -0.09 -0.68
      2      0.21  2.73
b     1      1.25  0.43
      2      1.52  0.63
c     1      1.31 -0.75
      2     -0.20 -1.08

#인덱싱 및 슬라이딩

In [194]:
population['인천시', 2010]

2757296

In [196]:
population[:,2010]

행정구역
서울시    10312545
부산시     2567910
인천시     2757296
대구시     2511676
대전시     1503664
광주시     1454636
dtype: int64

In [197]:
population[population>2000]

행정구역  년도  
서울시   2010    10312545
      2020     9720846
부산시   2010     2567910
      2020     3404423
인천시   2010     2757296
      2020     2947217
대구시   2010     2511676
      2020     2427954
대전시   2010     1503664
      2020     1471040
광주시   2010     1454636
      2020     1455048
dtype: int64

In [198]:
population[['대구시','대전시']]

행정구역  년도  
대구시   2010    2511676
      2020    2427954
대전시   2010    1503664
      2020    1471040
dtype: int64

In [199]:
mdf['c2',1]

name1  name2
a      1       -0.09
       2        0.21
b      1        1.25
       2        1.52
c      1        1.31
       2       -0.20
Name: (c2, 1), dtype: float64

In [200]:
mdf.iloc[:3,:4]

col_name1      c1          c2      
col_name_2      1     2     1     2
name1 name2                        
a     1     -0.05 -0.38 -0.09 -0.68
      2      0.57 -1.94  0.21  2.73
b     1     -1.31  0.04  1.25  0.43

In [201]:
mdf.loc[:,('c2',1)]

name1  name2
a      1       -0.09
       2        0.21
b      1        1.25
       2        1.52
c      1        1.31
       2       -0.20
Name: (c2, 1), dtype: float64

In [203]:
idx_slice=pd.IndexSlice
mdf.loc[idx_slice[:,2],idx_slice[:,2]]

col_name1      c1    c2    c3
col_name_2      2     2     2
name1 name2                  
a     2     -1.94  2.73  0.72
b     2      0.65  0.63  0.12
c     2     -1.45 -1.08 -0.03

#다중 인텍싱 재정렬

In [204]:
mdf

col_name1      c1          c2          c3      
col_name_2      1     2     1     2     1     2
name1 name2                                    
a     1     -0.05 -0.38 -0.09 -0.68 -0.16  0.99
      2      0.57 -1.94  0.21  2.73  1.10  0.72
b     1     -1.31  0.04  1.25  0.43 -0.81  0.77
      2     -1.70  0.65  1.52  0.63  1.20  0.12
c     1      0.55 -0.86  1.31 -0.75 -0.93 -1.86
      2      0.41 -1.45 -0.20 -1.08  1.07 -0.03

In [205]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [206]:
korea_df

인구수     남자수    여자수    남녀비율
서울  9700000  970000  97000  1000.0
인천  3400000  340000  34000  1000.0
부산  5600000  560000  56000  1000.0
대구  2000000  200000  20000  1000.0
광주  1000000  100000  10000  1000.0
대전  4500000  450000  45000  1000.0

In [207]:
korea_mdf

인구수      남자수      여자수        남녀비율
행정구역 년도                                          
서울시  2010  10312545  5111259  5201286   98.269140
     2020   9720846  4732275  4988571   94.862336
부산시  2010   2567910  1773170  1794740   98.798155
     2020   3404423  1668618  1735805   96.129346
인천시  2010   2757296  1390356  1367940  101.638668
     2020   2947217  1476813  1470404  100.435867
대구시  2010   2511676  1255245  1256431   99.905606
     2020   2427954  1198815  1229139   97.532907
대전시  2010   1503664   763648   750016  101.817561
     2020   1471040   734441   736599   99.707032
광주시  2010   1454636   721780   732856   98.488653
     2020   1455048   720060   734988   97.968946

In [208]:
korea_mdf=korea_mdf.sort_index()
korea_mdf

인구수      남자수      여자수        남녀비율
행정구역 년도                                          
광주시  2010   1454636   721780   732856   98.488653
     2020   1455048   720060   734988   97.968946
대구시  2010   2511676  1255245  1256431   99.905606
     2020   2427954  1198815  1229139   97.532907
대전시  2010   1503664   763648   750016  101.817561
     2020   1471040   734441   736599   99.707032
부산시  2010   2567910  1773170  1794740   98.798155
     2020   3404423  1668618  1735805   96.129346
서울시  2010  10312545  5111259  5201286   98.269140
     2020   9720846  4732275  4988571   94.862336
인천시  2010   2757296  1390356  1367940  101.638668
     2020   2947217  1476813  1470404  100.435867

In [211]:
korea_mdf['서울시':'인천시']

인구수      남자수      여자수        남녀비율
행정구역 년도                                          
서울시  2010  10312545  5111259  5201286   98.269140
     2020   9720846  4732275  4988571   94.862336
인천시  2010   2757296  1390356  1367940  101.638668
     2020   2947217  1476813  1470404  100.435867

In [212]:
korea_mdf.unstack(level=0)

인구수                                                   남자수           \
행정구역      광주시      대구시      대전시      부산시       서울시      인천시     광주시      대구시   
년도                                                                             
2010  1454636  2511676  1503664  2567910  10312545  2757296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...     여자수                                  남녀비율  \
행정구역     대전시      부산시  ...     대전시      부산시      서울시      인천시        광주시   
년도                     ...                                                 
2010  763648  1773170  ...  750016  1794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
행정구역        대구시         대전시        부산시        서울시         인천시  
년도                                                             
2010  99.905606  101.817561  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [213]:
korea_mdf.unstack(level=1)

인구수               남자수               여자수                 남녀비율  \
년도        2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                      
광주시    1454636  1455048   721780   720060   732856   734988   98.488653   
대구시    2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전시    1503664  1471040   763648   734441   750016   736599  101.817561   
부산시    2567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울시   10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천시    2757296  2947217  1390356  1476813  1367940  1470404  101.638668   

                  
년도          2020  
행정구역              
광주시    97.968946  
대구시    97.532907  
대전시    99.707032  
부산시    96.129346  
서울시    94.862336  
인천시   100.435867

In [214]:
korea_mdf.stack()

행정구역  년도        
광주시   2010  인구수     1.454636e+06
            남자수     7.217800e+05
            여자수     7.328560e+05
            남녀비율    9.848865e+01
      2020  인구수     1.455048e+06
            남자수     7.200600e+05
            여자수     7.349880e+05
            남녀비율    9.796895e+01
대구시   2010  인구수     2.511676e+06
            남자수     1.255245e+06
            여자수     1.256431e+06
            남녀비율    9.990561e+01
      2020  인구수     2.427954e+06
            남자수     1.198815e+06
            여자수     1.229139e+06
            남녀비율    9.753291e+01
대전시   2010  인구수     1.503664e+06
            남자수     7.636480e+05
            여자수     7.500160e+05
            남녀비율    1.018176e+02
      2020  인구수     1.471040e+06
            남자수     7.344410e+05
            여자수     7.365990e+05
            남녀비율    9.970703e+01
부산시   2010  인구수     2.567910e+06
            남자수     1.773170e+06
            여자수     1.794740e+06
            남녀비율    9.879815e+01
      2020  인구수     3.404423e+06
            남자수     1.6686

In [216]:
idx_flat=korea_mdf.reset_index(level=0)
idx_flat

행정구역       인구수      남자수      여자수        남녀비율
년도                                               
2010  광주시   1454636   721780   732856   98.488653
2020  광주시   1455048   720060   734988   97.968946
2010  대구시   2511676  1255245  1256431   99.905606
2020  대구시   2427954  1198815  1229139   97.532907
2010  대전시   1503664   763648   750016  101.817561
2020  대전시   1471040   734441   736599   99.707032
2010  부산시   2567910  1773170  1794740   98.798155
2020  부산시   3404423  1668618  1735805   96.129346
2010  서울시  10312545  5111259  5201286   98.269140
2020  서울시   9720846  4732275  4988571   94.862336
2010  인천시   2757296  1390356  1367940  101.638668
2020  인천시   2947217  1476813  1470404  100.435867

In [218]:
idx_flat=korea_mdf.reset_index(level=(0,1))
idx_flat

행정구역    년도       인구수      남자수      여자수        남녀비율
0   광주시  2010   1454636   721780   732856   98.488653
1   광주시  2020   1455048   720060   734988   97.968946
2   대구시  2010   2511676  1255245  1256431   99.905606
3   대구시  2020   2427954  1198815  1229139   97.532907
4   대전시  2010   1503664   763648   750016  101.817561
5   대전시  2020   1471040   734441   736599   99.707032
6   부산시  2010   2567910  1773170  1794740   98.798155
7   부산시  2020   3404423  1668618  1735805   96.129346
8   서울시  2010  10312545  5111259  5201286   98.269140
9   서울시  2020   9720846  4732275  4988571   94.862336
10  인천시  2010   2757296  1390356  1367940  101.638668
11  인천시  2020   2947217  1476813  1470404  100.435867

In [219]:
idx_flat.set_index(['행정구역','년도'])

인구수      남자수      여자수        남녀비율
행정구역 년도                                          
광주시  2010   1454636   721780   732856   98.488653
     2020   1455048   720060   734988   97.968946
대구시  2010   2511676  1255245  1256431   99.905606
     2020   2427954  1198815  1229139   97.532907
대전시  2010   1503664   763648   750016  101.817561
     2020   1471040   734441   736599   99.707032
부산시  2010   2567910  1773170  1794740   98.798155
     2020   3404423  1668618  1735805   96.129346
서울시  2010  10312545  5111259  5201286   98.269140
     2020   9720846  4732275  4988571   94.862336
인천시  2010   2757296  1390356  1367940  101.638668
     2020   2947217  1476813  1470404  100.435867

#데이터 연산

In [220]:
s=pd.Series(np.random.randint(0,10,5))
s

0    0
1    6
2    0
3    3
4    0
dtype: int64

In [222]:

df=pd.DataFrame(np.random.randint(0,10,(3,3)),
                columns=['A','B','C'])
df

A  B  C
0  9  0  3
1  9  5  0
2  8  3  7

In [223]:
np.exp(s)

0      1.000000
1    403.428793
2      1.000000
3     20.085537
4      1.000000
dtype: float64

In [224]:
np.cos(df*np.pi/4)

A         B         C
0  0.707107  1.000000 -0.707107
1  0.707107 -0.707107  1.000000
2  1.000000 -0.707107  0.707107

In [226]:
s1=pd.Series([1,3,5,7,9],index=[0,1,2,3,4,])
s2=pd.Series([2,4,6,8,10],index=[1,2,3,4,5])
s1+s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [228]:
s1.add(s2,fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [233]:
df1=pd.DataFrame(np.random.randint(0,20,(3,3)),
                    columns=list('ACD'))
df1

A   C   D
0   4  14  12
1   5  10  15
2  12   9  16

In [234]:
df2=pd.DataFrame(np.random.randint(0,20,(5,5)),
                    columns=list('BAECD'))
df2

B   A   E   C   D
0   2   4  13  19   7
1  15   2   9   5   7
2  11  16  16   6  11
3  17   5   9  16  18
4   5  18   3   2  15

In [235]:
df1+df2

A   B     C     D   E
0   8.0 NaN  33.0  19.0 NaN
1   7.0 NaN  15.0  22.0 NaN
2  28.0 NaN  15.0  27.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [236]:
fvalue=df1.stack().mean()
df1.add(df2,fill_value=fvalue)

A          B          C          D          E
0   8.000000  12.777778  33.000000  19.000000  23.777778
1   7.000000  25.777778  15.000000  22.000000  19.777778
2  28.000000  21.777778  15.000000  27.000000  26.777778
3  15.777778  27.777778  26.777778  28.777778  19.777778
4  28.777778  15.777778  12.777778  25.777778  13.777778

#연산자 범용 함수

In [239]:
a=np.random.randint(1,10,size=(3,3))
a

array([[2, 5, 4],
       [1, 2, 3],
       [6, 4, 2]])

In [240]:
a+a[0]

array([[ 4, 10,  8],
       [ 3,  7,  7],
       [ 8,  9,  6]])

In [241]:
df=pd.DataFrame(a,columns=list('ABC'))
df

A  B  C
0  2  5  4
1  1  2  3
2  6  4  2

In [242]:
df+df.iloc[0]

A   B  C
0  4  10  8
1  3   7  7
2  8   9  6

In [243]:
df.add(df.iloc[0])

A   B  C
0  4  10  8
1  3   7  7
2  8   9  6

## sub()/subtract()

In [244]:
a

array([[2, 5, 4],
       [1, 2, 3],
       [6, 4, 2]])

In [245]:
a+a[0]

array([[ 4, 10,  8],
       [ 3,  7,  7],
       [ 8,  9,  6]])

In [248]:
df.sub(df.iloc[0])

AttributeError: ignored

In [249]:
df.subtract(df['B'],axis=0)

AttributeError: ignored

##mul()/multiply

In [251]:
df=pd.DataFrame(a,columns=list('ABC'))
df


A  B  C
0  2  5  4
1  1  2  3
2  6  4  2

In [252]:
df.subtract(df['B'],axis=0)

A  B  C
0 -3  0 -1
1 -1  0  1
2  2  0 -2

In [253]:
df.mul(df.iloc[1])

A   B   C
0  2  10  12
1  1   4   9
2  6   8   6

In [254]:
df.multiply(df.iloc[2])

A   B  C
0  12  20  8
1   6   8  6
2  36  16  4

##truediv()/div()/divide()/floordiv()

In [255]:
a

array([[2, 5, 4],
       [1, 2, 3],
       [6, 4, 2]])

In [256]:
df

A  B  C
0  2  5  4
1  1  2  3
2  6  4  2

In [257]:
df/df.iloc[0]

A    B     C
0  1.0  1.0  1.00
1  0.5  0.4  0.75
2  3.0  0.8  0.50

In [258]:
df.truediv(df.iloc[0])

A    B     C
0  1.0  1.0  1.00
1  0.5  0.4  0.75
2  3.0  0.8  0.50

In [260]:
df.div(df.iloc[1])

A    B         C
0  2.0  2.5  1.333333
1  1.0  1.0  1.000000
2  6.0  2.0  0.666667

In [261]:
df.divide(df.iloc[2])

A     B    C
0  0.333333  1.25  2.0
1  0.166667  0.50  1.5
2  1.000000  1.00  1.0

In [262]:
a//a[0]

array([[1, 1, 1],
       [0, 0, 0],
       [3, 0, 0]])

In [263]:
df.floordiv(a[0])

A  B  C
0  1  1  1
1  0  0  0
2  3  0  0

##mod

In [264]:
a

array([[2, 5, 4],
       [1, 2, 3],
       [6, 4, 2]])

In [265]:
a%a[0]

array([[0, 0, 0],
       [1, 2, 3],
       [0, 4, 2]])

In [266]:
df

A  B  C
0  2  5  4
1  1  2  3
2  6  4  2

In [267]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  1  2  3
2  0  4  2

##pow

In [269]:
df.pow(df.iloc[0])

A     B    C
0   4  3125  256
1   1    32   81
2  36  1024   16

In [270]:
row=df.iloc[0,::2]
row

A    2
C    4
Name: 0, dtype: int64

In [273]:
df-row

A    0
C    0
Name: 0, dtype: int64

# 정렬